# Generated by Django 3.2.6 on 2022-11-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_Genre',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hate_Genre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_movies',
            field=models.ManyToManyField(related_name='favorite_user', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='user',
            name='hate_movies',
            field=models.ManyToManyField(related_name='hate_user', to='movies.Movie'),
        ),
    ]
