# Generated by Django 3.2.6 on 2022-11-16 04:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment'),
        ('accounts', '0004_auto_20221115_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='myGenre',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_Genre',
            field=models.ManyToManyField(related_name='favorite_user', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='hate_Genre',
            field=models.ManyToManyField(related_name='hate_user', to='movies.Genre'),
        ),
    ]
